// eslint-disable-next-line import/no-anonymous-default-export
export default {
  title: {
    textAlign: 'left',
    fontSize: '48px',
    marginTop: '3rem',
    marginLeft: '14rem',
    paddingRight: '.5rem',
    paddingBottom: '.5rem',
    borderBottom: '1px solid black',
    display: 'inline-block',
  },
  textContainer: {
    margin: '2rem 12rem 0 14rem',
  },
  imgContainer: {
    position: 'absolute',
    marginTop: '3rem',
    marginLeft: '15rem',
  },
  large: {
    width: '35rem',
    marginTop: '2rem',
    // opacity: '.9',
    display: 'inline-block',
    position: 'relative',
    zIndex: '1',
    boxShadow: '0px 0px 5px 5px rgba(255,255,255,.3)',
  },
  taylorAllison: {
    width: '35rem',
    marginTop: '2rem',
    // opacity: '.9',
    display: 'inline-block',
    position: 'relative',
    top: '18rem',
    right: '20rem',
    zIndex: '2',
    boxShadow: '0px 0px 5px 5px rgba(255,255,255,.3)',
  },
  pose: {
    width: '35rem',
    marginTop: '2rem',
    // opacity: '.9',
    display: 'inline-block',
    position: 'relative',
    bottom: '18rem',
    left: '42rem',
    zIndex: '3',
    boxShadow: '0px 0px 5px 5px rgba(255,255,255,.3)',
  },
  '@media screen and (min-width: 360px)': {},
  '@media screen and (min-width: 360px)': {},
  '@media screen and (min-width: 411px)': {},
  '@media screen and (min-width: 768px)': {},
  '@media screen and (min-width: 1366px)': {},
  '@media screen and (min-width: 1920px)': {},
};
