// eslint-disable-next-line import/no-anonymous-default-export
export default {
  // title: {
  //   textAlign: 'center',
  //   marginTop: '2rem',
  //   borderBottom: '1px solid black',
  //   display: 'block',
  // },
  logoContainer: {
    display: 'flex',
    justifyContent: 'center',
    paddingTop: '2rem',
    backgroundSize: 'cover',
    backgroundPosition: 'top center',
    backgroundRepeat: 'no-repeat',
    backgroundColor: 'black',
    backgroundAttachment: 'fixed',
  },
  logo: {
    maxWidth: '60vw',
  },
  textContainer: {
    margin: '2rem 2rem 0 2rem',
    color: 'black',
  },
  // rootsBackground: {
  //   backgroundSize: 'cover',
  //   backgroundPosition: 'top center',
  //   backgroundRepeat: 'no-repeat',
  //   backgroundColor: 'black',
  //   backgroundAttachment: 'fixed',
  // },
  imgContainer: {
    // position: 'absolute',
    // marginTop: '1rem',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: '5rem',
    // paddingBottom: '5rem',
    // backgroundSize: 'cover',
    // backgroundPosition: 'top center',
    // backgroundRepeat: 'no-repeat',
    // backgroundColor: 'black',
    // backgroundAttachment: 'fixed',
  },
  large: {
    width: '100vw',
    marginTop: '2rem',
    // marginRight: '1rem',
    // boxShadow: '0px 0px 5px 5px rgba(255,255,255,.3)',
  },
  taylorAllison: {
    width: '100vw',
    marginTop: '6rem',
    // marginLeft: '1rem',
    // boxShadow: '0px 0px 5px 5px rgba(255,255,255,.3)',
  },
  pose: {
    width: '100vw',
    marginTop: '6rem',
    // marginRight: '1rem',
    // boxShadow: '0px 0px 5px 5px rgba(255,255,255,.3)',
  },
  red_barn: {
    width: '100vw',
    marginTop: '6rem',
    // marginLeft: '1rem',
    // boxShadow: '0px 0px 5px 5px rgba(255,255,255,.3)',
  },
  '@media screen and (min-width: 360px)': {},
  '@media screen and (min-width: 375px)': {},
  '@media screen and (min-width: 411px)': {},
  '@media screen and (min-width: 768px)': {},
  '@media screen and (min-width: 1100px)': {
    logoContainer: {
      // display: 'block',
      // margin: '0 4rem 0 4rem',
      paddingTop: '4rem',
    },
    logo: {
      maxWidth: '40vw',
    },
    textContainer: {
      marginTop: '4rem !important',
    },
    imgContainer: {
      // paddingLeft: '10rem !important',
      paddingTop: '3rem',
      // paddingLeft: '15rem',
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-around',
    },
    large: {
      width: '25rem',
      marginTop: '2rem',
      // display: 'inline-block',
      // position: 'relative',
      // right: '10rem',
      // zIndex: '1',
      // boxShadow: '0px 0px 5px 5px rgba(255,255,255,.3)',
    },
    taylorAllison: {
      width: '25rem',
      marginTop: '2rem',
      // display: 'inline-block',
      // position: 'relative',
      // bottom: '4rem',
      // left: '5rem',
      // zIndex: '2',
      // boxShadow: '0px 0px 5px 5px rgba(255,255,255,.3)',
    },
    pose: {
      width: '25rem',
      marginTop: '2rem',
      // display: 'inline-block',
      // position: 'relative',
      // bottom: '10rem',
      // right: '12rem',
      // zIndex: '3',
      // boxShadow: '0px 0px 5px 5px rgba(255,255,255,.3)',
    },
    red_barn: {
      width: '25rem',
      marginTop: '2rem',
    },
  },
  '@media screen and (min-width: 1366px)': {
    rootsBackground: {
      height: '200vh',
    },
    title: {
      textAlign: 'left',
      fontSize: '48px',
      marginTop: '3rem',
      marginLeft: '14rem',
      paddingRight: '.5rem',
      paddingBottom: '.5rem',
      borderBottom: '1px solid black',
      display: 'inline-block',
    },
    textContainer: {
      margin: '2rem 12rem 0 14rem',
    },
    imgContainer: {
      // display: 'block',
      // position: 'absolute',
      paddingTop: '5rem',
      // paddingLeft: '15rem',
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-around',
    },
    large: {
      width: '35rem',
      // marginTop: '2rem',
      // display: 'inline-block',
      // marginRight: '1rem',
      // position: 'relative',
      // zIndex: '1',
      // boxShadow: '0px 0px 5px 5px rgba(255,255,255,.3)',
    },
    taylorAllison: {
      width: '35rem',
      // marginTop: '2rem',
      // display: 'inline-block',
      // marginLeft: '1rem',
      // position: 'relative',
      // bottom: '4rem',
      // left: '20rem',
      // zIndex: '2',
      // boxShadow: '0px 0px 5px 5px rgba(255,255,255,.3)',
    },
    pose: {
      width: '35rem',
      // marginRight: '1rem',
      // marginTop: '2rem',
      // display: 'inline-block',
      // position: 'relative',
      // bottom: '12rem',
      // left: '2rem',
      // zIndex: '3',
      // boxShadow: '0px 0px 5px 5px rgba(255,255,255,.3)',
    },
    red_barn: {
      width: '35rem',
      // marginTop: '2rem',
      // marginLeft: '1rem',
      // display: 'inline-block',
      // position: 'relative',
      // bottom: '12rem',
      // left: '2rem',
      // zIndex: '3',
      // boxShadow: '0px 0px 5px 5px rgba(255,255,255,.3)',
    },
  },
  '@media screen and (min-width: 1920px)': {},
};
